#!/usr/bin/env bash
#MERCIER Wilfried
#writes the list of galaxies with their full name (path+name) in the first column
#and their redshift from the .config file in the second one

outputName="list_gal"
folder="../data"
if [ $# -ge 1 ]
then
   outputName=$1
   if [ $# -ge 2 ]
   then
      folder=$2
   fi
fi

for i in $(find $folder -name *.config -type f -print)
do
   z=$(more $i | grep -F "REDSHIFT" | awk -F'= ' '{print $2}' | awk -F' /' '{print $1}')
   name=$(echo $i | awk -F/ '{for(i=1;i<=NF;i++) printf $i"/"}' | awk -F'.config' '{printf $1".config"}')
   LC_NUMERIC="en_US.UTF-8" printf "%-100s %f\n" "$name" "$z" >> $outputName
done


exit 0


